# PepperOpenDayDemo

## Environment Setup

In [1]:
# built-in imports
# !pip install requests
# !pip install speechrecognition==3.8.1
# !pip install paramiko
# !pip install pandas
# !pip install beautifulsoup4
# !pip install pocketsphinx
# !pip install scipy

bumperDetector = ALProxy("ALTouch", constants.PEPPER_HOST, constants.PEPPER_PORT)

memory = ALProxy("ALMemory", constants.PEPPER_HOST, constants.PEPPER_PORT)

# bumperDetector.subscribe("Device/SubDeviceList/Platform/Back/Bumper/Sensor/Value")



touch = bumperDetector.subscriber("TouchChanged")

status = memory.getData("SoundDetected")

print(touch)

print(status)



self.touch.signal.connect(functools.partial(self.onTouched, "TouchChanged"))



def onTouched():

    print("touched")

bumperDetector = ALProxy("ALTouch", PEPPER_HOST, PEPPER_PORT)

touch = bumperDetector.session.subscribe("TouchChanged")

memory = ALProxy("ALMemory", PEPPER_HOST, PEPPER_PORT)

bumperDetector.session().service

dir(bumperDetector.session())

touch = memory.subscribeToEvent()

dir(bumperDetector.session)

In [1]:
### Naoqi Related Imports ###
import naoqi
from naoqi import qi
from naoqi import ALProxy

### System Related Imports ###
import fileinput, os, shutil, sys, random, threading, time

### Flask Related Imports ###
import json, requests, time

### Speech Recognition Imports ###
import pandas as pd
import paramiko
import speech_recognition as sr

/usr/local/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.backends import default_backend


In [2]:
from prompts import *
import prompts
from fileTransfer import *
import fileTransfer as ft
from displayGeneration import *
import displayGeneration as dg
from interactiveControls import *
import interactiveControls as ic
from idle import *
import idle as idl
from humanInteraction import *
import humanInteraction as hi


# ### Custom File Handing Imports ###
# from fileTransfer import *

# ### Custom Idle Behaviour Imports ###
# from idle import *

# ### Custom Page Display Imports ###
# from displayGeneration import *

# ### Custom Interaction, Behaviour and Display Imports ###
# from interactiveControls import *

# ### Custom Hard-Coded Prompt Imports ###
# from prompts import *

# ### Main Interaction Imports ###
# from humanInteraction import *

## Constants

In [3]:
### Networking Constants ###
GPT_HOST = "10.104.23.208"
PEPPER_HOST = "10.104.23.185"
GPT_PORT = 8891
PEPPER_PORT = 9559

### Audio Processing Constants ###
PEPPER_RECORDINGS_PATH = "/home/nao/microphones/recording.wav"
SERVER_RECORDINGS_PATH = "recordings/recording.wav"

### Display Generation Constants ###
FILE_NAME_TEMP = "display.html"
PEPPER_HTML_PATH = "/home/nao/.local/share/PackageManager/apps/robot-page/html/"  # page.html"
PEPPER_PAGE_LANDING = PEPPER_HTML_PATH + "page.html" # '/home/nao/.local/share/PackageManager/apps/robot-page/html/page.html'
PEPPER_QR_LANDING = PEPPER_HTML_PATH + "webfiles/qr.png"  # switched slash direction
PEPPER_IMG_LANDING = PEPPER_HTML_PATH + "webfiles/img.png"  # switched slash direction
TEXT_BY_ID_PATH = "textbyID.csv"

## MAIN

In [ ]:
global idle
global responsesPipeline
global eyes

idle = idling()
eyes = EyesController()
eyes.startEyes("neutral")

try:
    track_head()

    while True:
        # Empty sentences list
        responsesPipeline = []
        
        # Idle behaviors to keep peppers temperature low
        idle.start_idle_behavior()

        # trigger smart listen
        detect()
        idle.stop()
        faceTracker()
        
        repeat = True
        rcount = 0
        # get course codes relevant to this
        # if query search is not successful, try the query search again until it is successful
        while (repeat and (rcount<4)):
            query = listen()
            repeat = queryCourseCodes(query, responsesPipeline, eyes)
            rcount += 1
            
        if (rcount>=4):
            continue
        
        #take a pause here for users to read the tablet
        time.sleep(5)
        
        #ask if they need specific details about a course
        repeat = True
        rcount = 0
        while repeat:
            query = listen()
            repeat = querySpecificCourse(query, responsesPipeline, eyes, rcount)
            rcount += 1
        
except Exception as e:
    print(e)
finally:
    stopListening()
    return_to_default_pos()
    idle = idling() 
    idle.start_idle_behavior()
    print('Goodbye')

copyfile successful
Sent to Pepper
0.782339334488
Detect complete
Recording is starting...
copyfile successful
Sent to Pepper
Timer is reached
Recording is stopping...
Sent from Pepper
[   40    20     0 ... -1250 -1465 -1740]
<type 'numpy.ndarray'>
Saved noise reduced audio file to recordings/rn_recording.wav

('Listen complete, This is what I heard: ', '%low_volume_error%')
copyfile successful
Sent to Pepper
Low volume error reached
Recording is starting...
copyfile successful
Sent to Pepper
Timer is reached
Recording is stopping...
Sent from Pepper
[   -60    -95   -125 ... -12265  -4005   3385]
<type 'numpy.ndarray'>
Saved noise reduced audio file to recordings/rn_recording.wav
('Listen complete, This is what I heard: ', u'hey can you tell me about artificial intelligence')
copyfile successful
Sent to Pepper
copyfile successful
 <li> Bachelor of Artificial Intelligence </li>
 <li> Master of Applied Artificial Intelligence (Professional) </li>
 <li> Master of Applied Artificial Inte

displayGeneration.py:182: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 182 of the file displayGeneration.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  target.replace_with(BeautifulSoup(subText))


Sent to Pepper
Sent to Pepper
Recording is starting...
copyfile successful
Sent to Pepper
Timer is reached
Recording is stopping...
Sent from Pepper
[ -500  -750 -1010 ...  1920  2415  2150]
<type 'numpy.ndarray'>
Saved noise reduced audio file to recordings/rn_recording.wav
('Listen complete, This is what I heard: ', u'smallest tomorrow')
('', '')
Recording is starting...
copyfile successful
Sent to Pepper
Timer is reached
Recording is stopping...
Sent from Pepper
[-105 -105 -100 ... -130  580  845]
<type 'numpy.ndarray'>
Saved noise reduced audio file to recordings/rn_recording.wav

('Listen complete, This is what I heard: ', '%low_volume_error%')
Low volume error reached
Recording is starting...
copyfile successful
Sent to Pepper
Timer is reached
Recording is stopping...
Sent from Pepper
[ -15  -15  -10 ... 1840 2145 2245]
<type 'numpy.ndarray'>
Saved noise reduced audio file to recordings/rn_recording.wav

('Listen complete, This is what I heard: ', '%low_volume_error%')
Low volume